name: awesome-install
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          wget -L https://raw.githubusercontent.com/ishxiao/awesome-install/main/swift-install.sh
          chmod +x ./swift-install.sh
          ./swift-install.sh