name: awesome-install
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x "${GITHUB_WORKSPACE}/swift-install.sh"
          "${GITHUB_WORKSPACE}/swift-install.sh"